from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys


REPO_ROOT = Path(__file__).resolve().parents[4]
TEMPLATE_ROOT = REPO_ROOT / ".agents/skills/dev-doc-harness/assets/templates"
ASSEMBLY_ROOT = TEMPLATE_ROOT / "assemblies"
GENERATED_NOTE = "<!-- Generated by assemble_templates.py; edit source blocks and manifests, then run the assembler. -->"
ASSEMBLIES = [
    (
        "large-phased-work-item-phase-plan.json",
        ".agents/skills/dev-doc-harness/assets/templates/large-phased-work-item-phase-plan.md",
    ),
    (
        "large-phased-work-item-spec.json",
        ".agents/skills/dev-doc-harness/assets/templates/large-phased-work-item-spec.md",
    ),
    (
        "small-medium-work-item-plan.json",
        ".agents/skills/dev-doc-harness/assets/templates/small-medium-work-item-plan.md",
    ),
    (
        "small-medium-work-item-spec.json",
        ".agents/skills/dev-doc-harness/assets/templates/small-medium-work-item-spec.md",
    ),
]


def load_manifests() -> list[dict[str, object]]:
    manifests: list[dict[str, object]] = []
    for manifest_name, expected_output in ASSEMBLIES:
        path = ASSEMBLY_ROOT / manifest_name
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("output") != expected_output:
            raise ValueError(f"{path}: output must be {expected_output}")
        data["_manifest_path"] = path
        manifests.append(data)
    return manifests


def repo_path(relative_path: str) -> Path:
    return REPO_ROOT / relative_path


def render_manifest(manifest: dict[str, object]) -> str:
    output = manifest.get("output")
    blocks = manifest.get("blocks")
    manifest_path = manifest.get("_manifest_path")
    if not isinstance(output, str):
        raise ValueError(f"{manifest_path}: output must be a string")
    if not isinstance(blocks, list) or not blocks:
        raise ValueError(f"{manifest_path}: blocks must be a non-empty list")

    parts = [GENERATED_NOTE]
    for block in blocks:
        if not isinstance(block, str):
            raise ValueError(f"{manifest_path}: block entries must be strings")
        if not block.startswith("blocks/") or "/" in block.removeprefix("blocks/"):
            raise ValueError(f"{manifest_path}: block must be a direct blocks/ entry: {block}")
        block_path = TEMPLATE_ROOT / block
        try:
            block_path.resolve().relative_to(TEMPLATE_ROOT.resolve())
        except ValueError:
            raise ValueError(f"{manifest_path}: block escapes template root: {block}") from None
        if not block_path.exists():
            raise FileNotFoundError(f"{manifest_path}: missing block {block}")
        parts.append(block_path.read_text(encoding="utf-8").strip())
    return "\n\n".join(parts).rstrip() + "\n"


def assembled_outputs() -> list[tuple[str, str]]:
    outputs: list[tuple[str, str]] = []
    for manifest in load_manifests():
        output = manifest.get("output")
        if not isinstance(output, str):
            raise ValueError(f"{manifest.get('_manifest_path')}: output must be a string")
        outputs.append((output, render_manifest(manifest)))
    return outputs


def list_templates() -> int:
    for manifest in load_manifests():
        output = manifest.get("output")
        blocks = manifest.get("blocks")
        print(output)
        if isinstance(blocks, list):
            for block in blocks:
                print(f"  - {block}")
    return 0


def check_templates() -> int:
    stale: list[str] = []
    for output, generated in assembled_outputs():
        output_path = repo_path(output)
        if not output_path.exists():
            stale.append(f"{output} (missing)")
            continue
        current = output_path.read_text(encoding="utf-8")
        if current != generated:
            stale.append(output)
    if stale:
        print("Stale assembled templates:")
        for path in stale:
            print(f"  - {path}")
        print("Run: python .agents/skills/dev-doc-harness/scripts/assemble_templates.py --write")
        return 1
    print("All assembled templates are current.")
    return 0


def write_templates() -> int:
    for output, generated in assembled_outputs():
        output_path = repo_path(output)
        output_path.write_text(generated, encoding="utf-8")

    freshness = check_templates()
    if freshness != 0:
        return freshness

    validator = REPO_ROOT / ".agents/skills/dev-doc-harness/scripts/test_harness_policy.py"
    result = subprocess.run([sys.executable, str(validator)], cwd=str(REPO_ROOT), check=False)
    return result.returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Assemble self-contained harness templates from ordered source blocks.")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--list", action="store_true", help="List assembled templates and ordered source blocks.")
    mode.add_argument("--check", action="store_true", help="Check generated templates without running full validation.")
    mode.add_argument("--write", action="store_true", help="Write generated templates, check freshness, then run validation.")
    args = parser.parse_args(argv)

    if args.list:
        return list_templates()
    if args.check:
        return check_templates()
    if args.write:
        return write_templates()
    return 2


if __name__ == "__main__":
    sys.exit(main())
